# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1
  cdk: signavio/cdk-orb@0.7.2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test
      - run:
          name: CDK Synth
          command: |
            npm run cdk synth
            npm run cdk deploy
